### ISSUE TITLE
what to do with ./data/ ./config/ ./services/ 

### ISSUE THREAD

**Issue by marc-portier** [vlizBE/vocabserver-deploy#2]
running docker-compose up introduces automatically these folders, owned by root

probably a very logical side-effect, but is now rather unexpected, so should get documented (see #1 )  as well as possibly be added to .gitignore to avoid these ever getting part of the repo?

**Comment by cedricdcc** [comment]
In vocabserver app the ./data folder holds all the temp data that can be reused  if the containers crash so this can be put into the .gitignore file.

But the ./config folder was essential for the other containers to work. This info should have been placed in the containers themselves for deployment for the whole system to work.

Same with the contents of the ./services . The dockerfile should have taken care of this so it is not necessary to further pursue this issue
